In [6]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [4]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
zeros_a=np.zeros((3,3),dtype=float)
print(zeros_a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_a=np.ones((3,3),dtype=float)
print(ones_a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
r=arr.reshape(1,5)
print(r)#5 rows 2 columns

[[1. 2. 3. 4. 5.]]


In [8]:
s=arr[2:4]
print(s)

[3. 4.]


In [9]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)

[1 2 3 4 5 6 7 8]


In [10]:
b=np.split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [11]:
a=np.array([[1,2,3,8],[2,3,4,5]])
b=a.T
print(b)

[[1 2]
 [2 3]
 [3 4]
 [8 5]]


In [12]:
a=np.array([[1,2],[3,8]])
b=np.array([[2,3],[4,5]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[10 13]
 [38 49]]
EigResult(eigenvalues=array([-0.06771888, 59.06771888]), eigenvectors=array([[-0.79062941, -0.25610402],
       [ 0.61229497, -0.96664923]]))


In [16]:
a=np.loadtxt("/content/lilly.txt.txt",dtype=int)
b=np.savetxt("/content/lilly.txt.txt",a)
print(b)
print(a)

None
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


<ipython-input-16-9ef3341253ba>:1: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  a=np.loadtxt("/content/lilly.txt.txt",dtype=int)


In [14]:
a=np.arange(0,1000,5)
print(a)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [15]:
d=np.savetxt("/content/lilly.txt.txt",a)
print(d)
a=np.loadtxt("/content/lilly.txt.txt",dtype=int)
print(a)

None
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


<ipython-input-15-8abb6ea79bab>:3: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  a=np.loadtxt("/content/lilly.txt.txt",dtype=int)


In [17]:
a=np.random.rand()
print(a)
b=np.random.randint(2,10)
print(b)

0.9394505723120475
2


In [18]:
c=np.array([[1,2,3],[2,3,4]])
print(type(c))
print(c.ndim)
print(c.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [19]:
a=np.linspace(0.8,3,5)
print(a)

[0.8  1.35 1.9  2.45 3.  ]


In [20]:
a=np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [21]:
a=np.arange(24).reshape(3,2,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [22]:
a=np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
a=np.array(([1,2],[3,4,]))
b=np.array(([5,6],[7,8]))
print(a*b)
print(a@b)
c=np.dot(a,b)
print(c)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [24]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())
b=np.ones((2,3),dtype=int)
print(b.sum)
print(a.sum(axis=1))
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
<built-in method sum of numpy.ndarray object at 0x7a7bd60ca430>
[3 3]
[2 2 2]


In [25]:
c=np.random.random((2,12))
print(c)
a=np.floor(np.random.random((2,12)))
print(a)
a=np.ceil(np.random.random((2,12)))

[[0.88416797 0.05583279 0.28756939 0.79542712 0.52262635 0.3108685
  0.3530226  0.99025661 0.28132533 0.26321169 0.50239728 0.27323482]
 [0.65165863 0.7932862  0.56030552 0.73215257 0.63302741 0.28486773
  0.30982983 0.26114245 0.64209795 0.3400606  0.82448447 0.1001008 ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
from numpy import random
a=np.array(([1,2],[3,4,]))
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))

4
[2 4]
[3 4]


In [27]:
a=np.array([[1,2],[2,5]])
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))

[[1 3]
 [2 7]]
[[1 2]
 [3 7]]


In [28]:
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
#b=a.resize(3,2)
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [29]:
a=np.array([[1,2,3,4,5,6]])
a.resize(2,3)
b=np.array([[11,8,6,4,5,6]])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [11  8  6]
 [ 4  5  6]]
[[ 1  2  3 11  8  6]
 [ 4  5  6  4  5  6]]


In [30]:
a=np.arange(0,30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [31]:
a=10
print(a)

10


In [32]:
66/11

6.0

In [33]:
32//5

6

In [34]:

import numpy as np
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
a=np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [36]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [37]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [38]:
a=np.array([1.1,2.3,4.5,3.4,5.6,3.8,9.0])
np.rint(a)

array([1., 2., 4., 3., 6., 4., 9.])

In [39]:
a=np.array([1,4,0,5,6])
b=np.array([2,8,9,6,4])
print(np.true_divide(a,b))

[0.5        0.5        0.         0.83333333 1.5       ]


In [40]:
a=np.array([1.1,3.3,1.1,4.4])
print(np.unique(a))

[1.1 3.3 4.4]


In [41]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,6],[8,7]])
print(np.union1d(a,b))

[1 2 3 4 6 7 8]


In [42]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,6],[8,7]])
print(np.intersect1d(a,b))

[1]


In [43]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,6],[8,7]])
print(np.setdiff1d(a,b))

[2 3 4]


In [44]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [45]:
x=np.sin(0)
print(x)

0.0


In [46]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [47]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.mod(a,b)
print(c)

[10  0  0  0  0 10]


In [48]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)#element vise multiplication
print(c)

[ 0.5  1.  15.   2.   2.   2.4]


In [49]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)
c=np.matmul(a,b)
print(c)

[ 200  441   60  800 1250 1500]
4251


In [50]:
from numpy import random
x=random.normal(size=(2,3))
print(x)
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)



[[-1.01958347  1.40210312 -0.33588788]
 [ 0.9727252  -1.05406448  0.7155102 ]]
[[-0.22444654 -2.18155976  4.79571596]
 [-0.52806984  2.44633328 -3.25087961]]


In [51]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[ 5  8  7  5  3  5  5 10  5  5]


In [52]:
x=random.poisson(lam=2,size=10)
print(x)

[2 2 2 3 1 1 1 1 6 1]


In [53]:
x=random.choice([1,2,3,4,5])
print(x)

5


In [54]:
x=random.choice([3,5],p=[0.2,0.8],size=(3,5))
print(x)
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[5 3 5 5 5]
 [3 3 3 5 5]
 [5 5 3 5 5]]
[[3 3 3 3 3]
 [5 5 3 3 3]
 [5 5 3 5 5]]
